run:
name: CI/CD Wisecow

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: docker/setup-buildx-action@v3


      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/wisecow:latest .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/wisecow:latest

      - name: Set up kubectl
      - uses: actions/cache@v4


      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/
uses:
